-- News Table
create table news (
  id bigint generated by default as identity primary key,
  date date not null,
  category text not null,
  title text not null,
  href text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- IR Metrics Table
create table ir_metrics (
  id bigint generated by default as identity primary key,
  title text not null,
  value numeric not null,
  unit text,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
