-- News Table
create table news (
  id bigint generated by default as identity primary key,
  date date not null,
  category text not null,
  title text not null,
  href text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- IR Metrics Table
create table ir_metrics (
  id bigint generated by default as identity primary key,
  title text not null,
  value numeric not null,
  unit text,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Strategic Units Table
create table units (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  unit_name text not null,
  owner_id text not null,
  odometer numeric not null default 0,
  next_oil_change date,
  maintenance_note text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Consumables Table
create table consumables (
  id bigint generated by default as identity primary key,
  name text not null,
  level integer not null default 100 check (level >= 0 and level <= 100),
  max_capacity integer not null default 100,
  unit text not null,
  color text default 'bg-blue-500',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tools Table
create table tools (
  id bigint generated by default as identity primary key,
  name text not null,
  spec text,
  qty integer not null default 1,
  status text not null default 'Available', -- 'Available', 'In Use', 'Maintenance', 'Missing'
  location text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
