import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import { readFileSync } from 'fs';
dotenv.config({ path: '.env.local' });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

async function run() {
  // まず既存テーブルを確認
  const { data: tables } = await supabase
    .from('information_schema.tables')
    .select('table_name')
    .eq('table_schema', 'public');
  
  console.log('Existing tables:', tables?.map(t => t.table_name).join(', '));

  // unit_documentsテーブル作成
  const sql = `
    CREATE TABLE IF NOT EXISTS public.maintenance_logs (
      id bigint generated by default as identity primary key,
      unit_id bigint NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
      date date NOT NULL,
      log_type text NOT NULL DEFAULT 'maintenance',
      title text NOT NULL,
      details text,
      cost numeric DEFAULT 0,
      created_at timestamptz DEFAULT now() NOT NULL
    );

    CREATE TABLE IF NOT EXISTS public.unit_documents (
      id bigint generated by default as identity primary key,
      unit_id bigint NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
      title text NOT NULL,
      document_type text NOT NULL DEFAULT 'OTHER',
      file_url text NOT NULL,
      file_name text NOT NULL,
      file_size bigint DEFAULT 0,
      mime_type text,
      storage_path text NOT NULL,
      uploaded_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
      created_at timestamptz DEFAULT now() NOT NULL
    );

    ALTER TABLE public.maintenance_logs ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.unit_documents ENABLE ROW LEVEL SECURITY;

    CREATE INDEX IF NOT EXISTS idx_maintenance_logs_unit_id ON public.maintenance_logs(unit_id);
    CREATE INDEX IF NOT EXISTS idx_unit_documents_unit_id ON public.unit_documents(unit_id);
  `;

  // Use REST API to execute SQL via service role
  const response = await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/rest/v1/rpc/exec_sql`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'apikey': process.env.SUPABASE_SERVICE_ROLE_KEY,
      'Authorization': `Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`,
    },
    body: JSON.stringify({ sql }),
  });
  
  if (response.ok) {
    console.log('SQL executed successfully');
  } else {
    const text = await response.text();
    console.log('Response status:', response.status, text);
  }
}

run().catch(console.error);
