/**
 * リモートSupabaseに直接接続してunit_documentsとmaintenance_logsを作成する
 * POSTGRES_URL_NON_POOLINGを使用（マイグレーション等のDDLはpoolerでは動かない）
 */
import pg from 'pg';
import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

const { Client } = pg;

const client = new Client({
  host: process.env.POSTGRES_HOST,
  database: process.env.POSTGRES_DATABASE || 'postgres',
  user: process.env.POSTGRES_USER || 'postgres',
  password: process.env.POSTGRES_PASSWORD,
  port: 5432,
  ssl: { rejectUnauthorized: false },
});

async function run() {
  await client.connect();
  console.log('✅ Connected to remote Supabase DB');

  // 1. maintenance_logs テーブル
  await client.query(`
    CREATE TABLE IF NOT EXISTS public.maintenance_logs (
      id bigint generated by default as identity primary key,
      unit_id bigint NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
      date date NOT NULL,
      log_type text NOT NULL DEFAULT 'maintenance',
      title text NOT NULL,
      details text,
      cost numeric DEFAULT 0,
      created_at timestamptz DEFAULT now() NOT NULL
    );
  `);
  console.log('✅ maintenance_logs table ready');

  // 2. unit_documents テーブル
  await client.query(`
    CREATE TABLE IF NOT EXISTS public.unit_documents (
      id bigint generated by default as identity primary key,
      unit_id bigint NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
      title text NOT NULL,
      document_type text NOT NULL DEFAULT 'OTHER',
      file_url text NOT NULL,
      file_name text NOT NULL,
      file_size bigint DEFAULT 0,
      mime_type text,
      storage_path text NOT NULL,
      uploaded_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
      created_at timestamptz DEFAULT now() NOT NULL
    );
  `);
  console.log('✅ unit_documents table ready');

  // 3. RLS有効化
  await client.query(`ALTER TABLE public.maintenance_logs ENABLE ROW LEVEL SECURITY;`);
  await client.query(`ALTER TABLE public.unit_documents ENABLE ROW LEVEL SECURITY;`);
  console.log('✅ RLS enabled');

  // 4. RLSポリシー (IF NOT EXISTSで安全に)
  const policies = [
    // maintenance_logs
    `DO $$ BEGIN
      IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename='maintenance_logs' AND policyname='maintenance_logs_select_public') THEN
        CREATE POLICY "maintenance_logs_select_public" ON public.maintenance_logs FOR SELECT USING (true);
      END IF;
    END $$;`,
    `DO $$ BEGIN
      IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename='maintenance_logs' AND policyname='maintenance_logs_insert_authenticated') THEN
        CREATE POLICY "maintenance_logs_insert_authenticated" ON public.maintenance_logs FOR INSERT TO authenticated WITH CHECK (true);
      END IF;
    END $$;`,
    `DO $$ BEGIN
      IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename='maintenance_logs' AND policyname='maintenance_logs_update_authenticated') THEN
        CREATE POLICY "maintenance_logs_update_authenticated" ON public.maintenance_logs FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
      END IF;
    END $$;`,
    `DO $$ BEGIN
      IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename='maintenance_logs' AND policyname='maintenance_logs_delete_authenticated') THEN
        CREATE POLICY "maintenance_logs_delete_authenticated" ON public.maintenance_logs FOR DELETE TO authenticated USING (true);
      END IF;
    END $$;`,
    // unit_documents
    `DO $$ BEGIN
      IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename='unit_documents' AND policyname='unit_documents_select_public') THEN
        CREATE POLICY "unit_documents_select_public" ON public.unit_documents FOR SELECT USING (true);
      END IF;
    END $$;`,
    `DO $$ BEGIN
      IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename='unit_documents' AND policyname='unit_documents_insert_authenticated') THEN
        CREATE POLICY "unit_documents_insert_authenticated" ON public.unit_documents FOR INSERT TO authenticated WITH CHECK (true);
      END IF;
    END $$;`,
    `DO $$ BEGIN
      IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename='unit_documents' AND policyname='unit_documents_update_authenticated') THEN
        CREATE POLICY "unit_documents_update_authenticated" ON public.unit_documents FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
      END IF;
    END $$;`,
    `DO $$ BEGIN
      IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename='unit_documents' AND policyname='unit_documents_delete_authenticated') THEN
        CREATE POLICY "unit_documents_delete_authenticated" ON public.unit_documents FOR DELETE TO authenticated USING (true);
      END IF;
    END $$;`,
  ];

  for (const sql of policies) {
    await client.query(sql);
  }
  console.log('✅ RLS policies created');

  // 5. インデックス
  await client.query(`CREATE INDEX IF NOT EXISTS idx_maintenance_logs_unit_id ON public.maintenance_logs(unit_id);`);
  await client.query(`CREATE INDEX IF NOT EXISTS idx_unit_documents_unit_id ON public.unit_documents(unit_id);`);
  console.log('✅ Indexes created');

  // 6. 現在のユニット一覧確認
  const { rows } = await client.query(`SELECT id, slug, unit_name FROM public.units ORDER BY id;`);
  console.log('\n📋 Current units in DB:');
  rows.forEach(r => console.log(`  id=${r.id}  slug=${r.slug}  name=${r.unit_name}`));

  await client.end();
  console.log('\n🎉 Migration complete!');
}

run().catch(err => {
  console.error('❌ Error:', err.message);
  process.exit(1);
});
