import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

async function run() {
  console.log('Connecting to:', process.env.NEXT_PUBLIC_SUPABASE_URL);

  // Create maintenance_logs
  const { error: e1 } = await supabase.rpc('exec', { 
    sql: `
      CREATE TABLE IF NOT EXISTS public.maintenance_logs (
        id bigint generated by default as identity primary key,
        unit_id bigint NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
        date date NOT NULL,
        log_type text NOT NULL DEFAULT 'maintenance',
        title text NOT NULL,
        details text,
        cost numeric DEFAULT 0,
        created_at timestamptz DEFAULT now() NOT NULL
      );
    `
  });
  
  if (e1) {
    console.log('maintenance_logs rpc error, trying direct query...');
    // Try alternative approach using PostgREST
    const res = await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/rest/v1/`, {
      method: 'GET',
      headers: {
        'apikey': process.env.SUPABASE_SERVICE_ROLE_KEY,
        'Authorization': `Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`,
      },
    });
    console.log('API available:', res.status);
  }

  // Check if unit_documents exists
  const { data, error } = await supabase.from('unit_documents').select('id').limit(1);
  console.log('unit_documents check:', { data, error: error?.message });

  const { data: d2, error: e2 } = await supabase.from('maintenance_logs').select('id').limit(1);
  console.log('maintenance_logs check:', { data: d2, error: e2?.message });
}

run().catch(console.error);
