-- Drop the existing tables because they have an old/incorrect schema
DROP TABLE IF EXISTS public.unit_documents CASCADE;
DROP TABLE IF EXISTS public.maintenance_logs CASCADE;

-- Recreate maintenance_logs
CREATE TABLE public.maintenance_logs (
  id bigint generated by default as identity primary key,
  unit_id bigint NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
  date date NOT NULL,
  log_type text NOT NULL DEFAULT 'maintenance',
  title text NOT NULL,
  details text,
  cost numeric DEFAULT 0,
  created_at timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.maintenance_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for authenticated users" ON public.maintenance_logs FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users" ON public.maintenance_logs FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users" ON public.maintenance_logs FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for authenticated users" ON public.maintenance_logs FOR DELETE TO authenticated USING (true);

-- Recreate unit_documents
CREATE TABLE public.unit_documents (
  id bigint generated by default as identity primary key,
  unit_id bigint NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
  title text NOT NULL,
  document_type text NOT NULL,
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_size bigint NOT NULL,
  mime_type text,
  storage_path text,
  uploaded_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.unit_documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for all users" ON public.unit_documents FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.unit_documents FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON public.unit_documents FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for authenticated users only" ON public.unit_documents FOR DELETE TO authenticated USING (true);
