-- ============================================================
-- Migration: Create unit_documents and maintenance_logs tables
-- Date: 2026-07-11
-- Purpose: 機動戦力詳細画面へのマニュアル・書類アップロード機能を実装する
-- ============================================================

-- ─────────────────────────────────────────
-- maintenance_logs テーブル（整備記録）
-- ※ 既存で存在する可能性があるため IF NOT EXISTS で安全に作成
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.maintenance_logs (
  id bigint generated by default as identity primary key,
  unit_id bigint NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
  date date NOT NULL,
  log_type text NOT NULL DEFAULT 'maintenance',
  title text NOT NULL,
  details text,
  cost numeric DEFAULT 0,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- ─────────────────────────────────────────
-- unit_documents テーブル（マニュアル・書類）
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.unit_documents (
  id bigint generated by default as identity primary key,
  unit_id bigint NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
  title text NOT NULL,
  document_type text NOT NULL DEFAULT 'OTHER',
  -- document_type: 'MANUAL' | 'PARTS_LIST' | 'CERTIFICATE' | 'INSPECTION' | 'OTHER'
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_size bigint DEFAULT 0,  -- bytes
  mime_type text,
  storage_path text NOT NULL, -- Supabase Storage内のパス (削除時に使用)
  uploaded_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- ─────────────────────────────────────────
-- RLS: maintenance_logs
-- 読み取り: 全員（ユニット詳細ページで公開表示）
-- 書き込み: 認証済みユーザーのみ
-- ─────────────────────────────────────────
ALTER TABLE public.maintenance_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "maintenance_logs_select_public"
  ON public.maintenance_logs FOR SELECT
  USING (true);

CREATE POLICY "maintenance_logs_insert_authenticated"
  ON public.maintenance_logs FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "maintenance_logs_update_authenticated"
  ON public.maintenance_logs FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "maintenance_logs_delete_authenticated"
  ON public.maintenance_logs FOR DELETE
  TO authenticated
  USING (true);

-- ─────────────────────────────────────────
-- RLS: unit_documents
-- 読み取り: 全員（マニュアルはメンバー共有情報）
-- 書き込み: 認証済みユーザーのみ
-- ─────────────────────────────────────────
ALTER TABLE public.unit_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "unit_documents_select_public"
  ON public.unit_documents FOR SELECT
  USING (true);

CREATE POLICY "unit_documents_insert_authenticated"
  ON public.unit_documents FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "unit_documents_update_authenticated"
  ON public.unit_documents FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "unit_documents_delete_authenticated"
  ON public.unit_documents FOR DELETE
  TO authenticated
  USING (true);

-- ─────────────────────────────────────────
-- インデックス (パフォーマンス最適化)
-- ─────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_maintenance_logs_unit_id ON public.maintenance_logs(unit_id);
CREATE INDEX IF NOT EXISTS idx_unit_documents_unit_id ON public.unit_documents(unit_id);
